### ISSUE TITLE
Embeddings are ambiguous

### ISSUE THREAD

**Issue by zrho** [zrho/homotopy-rs#1]
An embedding of a diagram `needle` in a bigger diagram `haystack` is represented as a sequence of regular heights by which the contents of `needle` are to be shifted to constitute a subdiagram of `haystack`. While this works in most situations, this appears to be ambiguous in some situations: Suppose that `haystack` is a 2-diagram with two scalars positioned on the same height. Both the left and the right scalar then are represented by the same embedding `[0, 0]`.

In the type checking code, embeddings are represented more precisely. That representation of embeddings is currently not exported since it is quite a lot more expensive and wasn't deemed necessary for attachment or finding embedded subdiagrams. Given the ambiguity problem with sequences of regular heights, the precise notion of embedding might need to become standard. This would have some implications on the API which aren't entirely clear yet.

Alternatively, we could restrict (outside of typechecking) to a notion of embedding in which ambiguous cases are excluded. An embedding could, for instance, be declared valid only if the `haystack` diagram does not contain any non-trivial content on the sides of the `needle`. This appears to match the behaviour of the JS version, although I don't think this has been deliberate.

**Comment by zrho** [comment]
The restricted notion of embeddings that excludes non-identities on the side appears precisely to be what was previously implemented, so it appears sufficient.

**Comment by jamievicary** [comment]
I just saw this old thread. I can confirm that in the JS version, an attachment is only allowed if the needle subdiagram has identities to the left and right. There is a good reason for this, as I guess you are aware -- without boxing, the attachment will otherwise not be possible.
